In [3]:
from transformers import BertTokenizer, BertModel
tokenizer2 = BertTokenizer.from_pretrained('bert-base-uncased')
model2 = BertModel.from_pretrained('bert-base-uncased', output_hidden_states = True, output_attentions = True)
model2.eval()

import torch
from pytorch_pretrained_bert import BertTokenizer, BertModel
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained('bert-base-uncased')
model.eval()

BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(30522, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): BertLayerNorm()
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0): BertLayer(
        (attention): BertAttention(
          (self): BertSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): BertLayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
        (intermediate): BertIntermediate(
          (dense): Lin

In [2]:
def get_tokenized_text(text):
    marked_text = "[CLS] " + text + " [SEP]"
    tokenized_text = tokenizer.tokenize(marked_text)
    return tokenized_text

In [4]:
text = "here is some text to encode"

# Tokenizer, model is from PPB (pytorch pretrained bert), Tokenizer2, model2 is from Transformers

In [5]:
doc = get_tokenized_text(text)
indexed_tokens = tokenizer.convert_tokens_to_ids(doc)
indexed_tokens

[101, 2182, 2003, 2070, 3793, 2000, 4372, 16044, 102]

In [6]:
torch.tensor([tokenizer2.encode(text, add_special_tokens=True)])

tensor([[  101,  2182,  2003,  2070,  3793,  2000,  4372, 16044,   102]])

# Tokenization is identical

# Encoded Layers from Pytorch Pretrained Bert

In [22]:
indexed_tokens = tokenizer.convert_tokens_to_ids(doc)
segments_ids = [1] * len(doc)

tokens_tensor = torch.tensor([indexed_tokens])
segments_tensors = torch.tensor([segments_ids])

with torch.no_grad():
    encoded_layers, _ = model(tokens_tensor, segments_tensors)

In [23]:
encoded_layers, len(encoded_layers)

([tensor([[[ 0.1175, -0.0414, -0.0293,  ...,  0.0107,  0.0555,  0.0465],
           [-0.8823,  0.6766, -1.4811,  ...,  0.2850,  0.5769,  0.4403],
           [-0.8768, -0.7149, -0.6195,  ...,  0.1722,  0.0610,  0.3234],
           ...,
           [ 1.4578, -1.6513, -0.9443,  ..., -0.4543,  0.8893, -0.1556],
           [ 0.6253, -0.6459,  0.1528,  ..., -0.1199, -0.1559,  0.7200],
           [ 0.0278, -0.1232, -0.0390,  ...,  0.0574,  1.0494,  0.0589]]]),
  tensor([[[-0.0271, -0.1631, -0.1662,  ...,  0.2235,  0.1752, -0.0263],
           [-1.1879,  1.2727, -0.8647,  ..., -0.0647,  0.9201,  0.1990],
           [-0.7484, -0.5935, -0.1351,  ...,  0.2642, -0.1155,  0.3915],
           ...,
           [ 1.7911, -1.1837, -0.6306,  ..., -1.1321,  1.0605, -0.3709],
           [ 1.1517, -0.0946,  0.4455,  ..., -0.3401,  0.3848,  0.2715],
           [-0.1580,  0.0727,  0.0607,  ...,  0.3485,  0.8295, -0.2014]]]),
  tensor([[[ 0.0180, -0.2131, -0.0200,  ...,  0.1586,  0.1851,  0.0642],
           [-

In [24]:
input_ids = torch.tensor([tokenizer2.encode(text, add_special_tokens=True)])  # Add special tokens takes care of adding [CLS], [SEP], <s>... tokens in the right way for each model.
with torch.no_grad():
    all_hidden_states, all_attentions = model2(input_ids)[-2:]


In [25]:
len(all_hidden_states)

13

In [26]:
all_hidden_states[1:]

(tensor([[[ 0.1049, -0.0210, -0.0417,  ...,  0.0093,  0.0346,  0.0303],
          [-0.7899,  0.9358, -1.3953,  ...,  0.2927,  0.5613,  0.5016],
          [-0.8396, -0.5291, -0.5162,  ...,  0.1113,  0.1075,  0.3630],
          ...,
          [ 1.5062, -1.4110, -0.8548,  ..., -0.4749,  0.8963, -0.0522],
          [ 0.6532, -0.4377,  0.2107,  ..., -0.1252, -0.1105,  0.7984],
          [-0.0599, -0.1133, -0.0353,  ..., -0.2013,  0.8951, -0.0430]]]),
 tensor([[[-0.0125, -0.2191, -0.2090,  ...,  0.2493,  0.1552, -0.0491],
          [-1.1062,  1.4273, -0.8342,  ...,  0.0458,  0.8728,  0.2475],
          [-0.7080, -0.3701, -0.0666,  ...,  0.2603, -0.0469,  0.4278],
          ...,
          [ 1.8732, -0.9943, -0.6085,  ..., -0.9808,  0.9922, -0.2782],
          [ 1.1598,  0.1219,  0.4285,  ..., -0.2322,  0.4805,  0.3791],
          [-0.1454, -0.0715,  0.0495,  ...,  0.0927,  0.6526, -0.2409]]]),
 tensor([[[ 0.0568, -0.3138, -0.0495,  ...,  0.1891,  0.1856,  0.0601],
          [-1.4235,  1.0459,

# LETS NOT GIVE SEGMENT IDS AS INPUT TO PPB MODEL.

In [27]:
indexed_tokens = tokenizer.convert_tokens_to_ids(doc)
segments_ids = [1] * len(doc)

tokens_tensor = torch.tensor([indexed_tokens])
segments_tensors = torch.tensor([segments_ids])

with torch.no_grad():
    encoded_layers, _ = model(tokens_tensor)
encoded_layers


[tensor([[[ 0.1049, -0.0210, -0.0417,  ...,  0.0093,  0.0346,  0.0303],
          [-0.7899,  0.9358, -1.3953,  ...,  0.2927,  0.5613,  0.5016],
          [-0.8396, -0.5291, -0.5162,  ...,  0.1113,  0.1075,  0.3630],
          ...,
          [ 1.5062, -1.4110, -0.8548,  ..., -0.4749,  0.8963, -0.0522],
          [ 0.6532, -0.4377,  0.2107,  ..., -0.1252, -0.1105,  0.7984],
          [-0.0599, -0.1133, -0.0353,  ..., -0.2013,  0.8951, -0.0430]]]),
 tensor([[[-0.0125, -0.2191, -0.2090,  ...,  0.2493,  0.1552, -0.0491],
          [-1.1062,  1.4273, -0.8342,  ...,  0.0458,  0.8728,  0.2475],
          [-0.7080, -0.3701, -0.0666,  ...,  0.2603, -0.0469,  0.4278],
          ...,
          [ 1.8732, -0.9943, -0.6085,  ..., -0.9808,  0.9922, -0.2782],
          [ 1.1598,  0.1219,  0.4285,  ..., -0.2322,  0.4805,  0.3791],
          [-0.1454, -0.0715,  0.0495,  ...,  0.0927,  0.6526, -0.2409]]]),
 tensor([[[ 0.0568, -0.3138, -0.0495,  ...,  0.1891,  0.1856,  0.0601],
          [-1.4235,  1.0459,

# The results are same now with PPB and Transformers

In [30]:
def get_embeddings_concat_last_4_with_segment_ids(doc):
    indexed_tokens = tokenizer.convert_tokens_to_ids(doc)
    segments_ids = [1] * len(doc)

    tokens_tensor = torch.tensor([indexed_tokens])
    segments_tensors = torch.tensor([segments_ids])

    with torch.no_grad():
        encoded_layers, _ = model(tokens_tensor, segments_tensors)  

        token_embeddings = torch.stack(encoded_layers, dim=0)
        token_embeddings = torch.squeeze(token_embeddings, dim=1)
        token_embeddings = token_embeddings.permute(1,0,2)

    token_vecs_cat = []
    for token in token_embeddings:
        cat_vec = torch.cat((token[-4], token[-3], token[-2], token[-1]), dim=0)
        token_vecs_cat.append(cat_vec)
    return token_vecs_cat

def get_embeddings_concat_last_4_without_segment_ids(doc):
    indexed_tokens = tokenizer.convert_tokens_to_ids(doc)
    tokens_tensor = torch.tensor([indexed_tokens])

    with torch.no_grad():
        encoded_layers, _ = model(tokens_tensor)  

        token_embeddings = torch.stack(encoded_layers, dim=0)
        token_embeddings = torch.squeeze(token_embeddings, dim=1)
        token_embeddings = token_embeddings.permute(1,0,2)

    token_vecs_cat = []
    for token in token_embeddings:
        cat_vec = torch.cat((token[-1], token[-2], token[-3], token[-4]), dim=0)
        token_vecs_cat.append(cat_vec)
    return token_vecs_cat

def get_embeddings_transformers(text, tokenizer2, model2):
    input_ids = torch.tensor([tokenizer2.encode(text, add_special_tokens=True)])  # Add special tokens takes care of adding [CLS], [SEP], <s>... tokens in the right way for each model.
    with torch.no_grad():
        all_hidden_states, all_attentions = model2(input_ids)[-2:]
    pooled_output = torch.cat(tuple([all_hidden_states[i] for i in [-4, -3, -2, -1]]), dim=-1)
    return pooled_output

# Comparison in similarity of tokens for PPB with and without segment ids

In [37]:
import numpy as np
def get_cosine(a,b):
    dot = np.dot(a, b)
    norma = np.linalg.norm(a)
    normb = np.linalg.norm(b)
    cos = dot / (norma * normb)
    return cos


In [33]:
query1 = "software"
query2 = "smoking kills"
trans_query2 = get_tokenized_text(query2)
vec2 = get_embeddings_concat_last_4_with_segment_ids(trans_query2)
trans_query1 = get_tokenized_text(query1)
vec1 = get_embeddings_concat_last_4_with_segment_ids(trans_query1)

In [38]:
for i in range(len(vec1)):
    for j in range(len(vec2)):
        print(get_cosine(vec1[i], vec2[j]), trans_query1[i], trans_query2[j])

0.672423 [CLS] [CLS]
0.33314344 [CLS] smoking
0.43435374 [CLS] kills
-0.058492318 [CLS] [SEP]
0.39661705 software [CLS]
0.39606315 software smoking
0.48784116 software kills
0.025117889 software [SEP]
-0.015437898 [SEP] [CLS]
-0.0026445969 [SEP] smoking
0.012134828 [SEP] kills
0.9721178 [SEP] [SEP]


In [39]:
query1 = "software"
query2 = "smoking kills"
trans_query2 = get_tokenized_text(query2)
vec2 = get_embeddings_concat_last_4_without_segment_ids(trans_query2)
trans_query1 = get_tokenized_text(query1)
vec1 = get_embeddings_concat_last_4_without_segment_ids(trans_query1)
for i in range(len(vec1)):
    for j in range(len(vec2)):
        print(get_cosine(vec1[i], vec2[j]), trans_query1[i], trans_query2[j])

0.7332338 [CLS] [CLS]
0.30889347 [CLS] smoking
0.41676685 [CLS] kills
-0.057872273 [CLS] [SEP]
0.347957 software [CLS]
0.35621607 software smoking
0.60760146 software kills
0.031820424 software [SEP]
-0.024245258 [SEP] [CLS]
-0.008735579 [SEP] smoking
0.034555774 [SEP] kills
0.971085 [SEP] [SEP]


# software got very similar to kills when segment ids are not used

In [40]:
query1 = "software"
query2 = "software engineering skills"
trans_query2 = get_tokenized_text(query2)
vec2 = get_embeddings_concat_last_4_without_segment_ids(trans_query2)
trans_query1 = get_tokenized_text(query1)
vec1 = get_embeddings_concat_last_4_without_segment_ids(trans_query1)
for i in range(len(vec1)):
    for j in range(len(vec2)):
        print(get_cosine(vec1[i], vec2[j]), trans_query1[i], trans_query2[j])

0.7137769 [CLS] [CLS]
0.25000635 [CLS] software
0.36119947 [CLS] engineering
0.37555072 [CLS] skills
-0.058984034 [CLS] [SEP]
0.40880308 software [CLS]
0.5280046 software software
0.44189313 software engineering
0.58193666 software skills
0.022055043 software [SEP]
-0.030546578 [SEP] [CLS]
0.03651763 [SEP] software
0.01451009 [SEP] engineering
0.053263895 [SEP] skills
0.9806409 [SEP] [SEP]


In [41]:
query1 = "software"
query2 = "software engineering skills"
trans_query2 = get_tokenized_text(query2)
vec2 = get_embeddings_concat_last_4_with_segment_ids(trans_query2)
trans_query1 = get_tokenized_text(query1)
vec1 = get_embeddings_concat_last_4_with_segment_ids(trans_query1)
for i in range(len(vec1)):
    for j in range(len(vec2)):
        print(get_cosine(vec1[i], vec2[j]), trans_query1[i], trans_query2[j])

0.6773981 [CLS] [CLS]
0.2885203 [CLS] software
0.41684645 [CLS] engineering
0.41811934 [CLS] skills
-0.06042074 [CLS] [SEP]
0.39397994 software [CLS]
0.636608 software software
0.55451936 software engineering
0.55175096 software skills
0.025576958 software [SEP]
-0.020932069 [SEP] [CLS]
0.044678118 [SEP] software
0.029137056 [SEP] engineering
0.042281345 [SEP] skills
0.9843705 [SEP] [SEP]


In [42]:
query1 = "software"
query2 = "software engineering skills"
trans_query2 = get_tokenized_text(query2)
vec2 = get_embeddings_concat_last_4_without_segment_ids(trans_query2)
trans_query1 = get_tokenized_text(query1)
vec1 = get_embeddings_concat_last_4_without_segment_ids(trans_query1)
for i in range(len(vec1)):
    for j in range(len(vec2)):
        print(get_cosine(vec1[i], vec2[j]), trans_query1[i], trans_query2[j])

0.7137769 [CLS] [CLS]
0.25000635 [CLS] software
0.36119947 [CLS] engineering
0.37555072 [CLS] skills
-0.058984034 [CLS] [SEP]
0.40880308 software [CLS]
0.5280046 software software
0.44189313 software engineering
0.58193666 software skills
0.022055043 software [SEP]
-0.030546578 [SEP] [CLS]
0.03651763 [SEP] software
0.01451009 [SEP] engineering
0.053263895 [SEP] skills
0.9806409 [SEP] [SEP]


# WHAT IS THE IMPLICATION OF THIS?

# this why i was getting bad results with Transformers